server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/museum
    username: museum
    password: museum_dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: "replace-this-with-a-long-secret-key-at-least-32-bytes"
    expiration-seconds: 3600
